import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Food Order App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-base-100 flex flex-col w-full h-screen p-0 m-0`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
