export const metadata = {
  title: 'Food Order | Recommendations',
  description: 'Generated by create next app',
};

export default function RecommendationLayout({ children }) {
  return children;
}
